### ISSUE TITLE
Auto Authorization does not work

### ISSUE THREAD

**Issue by gerhard-thompson** [zerotier/chef-zerotier#5]
Chef Log:
```Recipe: zerotier::ohai_plugin
  * ohai_plugin[zerotier_ohai] action create
    * directory[/etc/chef/ohai/plugins] action create (skipped due to not_if)
    * template[/etc/chef/ohai/plugins/zerotier_ohai.rb] action create (up to date)
    * ohai[zerotier_ohai] action nothing (skipped due to action :nothing)
     (up to date)
Recipe: zerotier::join_networks
  * zerotier_network[XXXXXXXXXXXXXXX] action join (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 2/14 resources updated in 05 seconds
root@masterchef:~/chef-repo/cookbooks# zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks XXXXXXXXXXXXXXX  AA:BB:CC:DD:EE:FF ACCESS_DENIED PRIVATE ztbpaj2l7d -
 ```

I dont know how to debug the LWRP, but i cant rebuild that Request and there i get this error
> {"type":"internal","message":"Error marshalling json"}

But even if do a Request with the complete Payload (getting it with GET Request before), not just the small Part, replace the "authorized: false" with true, it just does not authorize the Node.

**Comment by hacktron95** [comment]
i just got the same error while trying to update/add member into the network using the controller API,
I solved it by passing an empty JSON object `{}` in the request body

**Comment by someara** [comment]
Hey! Sorry for sleeping on this for so long... closing for now, due to @tas50's modernization work. Feel free to re-open if this is still an issue.
